### ISSUE TITLE
Pause Button even if app is not focused

### ISSUE THREAD

**Issue by musictopia2** [westbrookmd/MediaDock#3]
Would you like a way to make it where even if you somehow had another app on top you can still pause for example?
Because I have a library that can be used that has different key events.  So even if somebody is for example in notepad and want to pause without using the mouse, you can.  The nuget package is this one.
 https://github.com/musictopia2/WindowsKeyboardCapture
This has a nuget package as well.  I had somebody many years ago do that function for me because I have a media player where I want to be able to pause a song even if the program is minimized (or if another app is full screen) like a game.

**Comment by westbrookmd** [comment]
I originally pictured MediaDock to be floating on the desktop or on top of other windows but this could still add a lot of value.

Global hotkeys could be a convenient feature for users without media keys built into their keyboard and users who don't want MediaDock on top of other windows. I'll keep the issue open until I figure out whether to add this to the planned features.

Thanks for the suggestion and nuget package to potentially use!

**Comment by westbrookmd** [comment]
@musictopia2 I've added this to the roadmap. Thanks!
